### PR TITLE
Updated server.js

### PR DESCRIPTION
**Pull request by xiaojoey**

### CODE REVIEW

**Comment by samseaver** [comment]
First task for the quarter is to submit all changes made to the express JS code under this PR.

I will be able to clone the files once done, and test it on my laptop: this will require documentation from you to tell me how to effectively test your changes.

**Comment by xiaojoey** [comment]
I commented my code and added instructions to a readme in the express folder

**Comment by xiaojoey** [comment]
I've fixed some of the requests and changed the Monster urls in the Vue server so they point toward the Express server now. The upload, submit job, and retrieve functions work on the development build. The file paths in the express server are currently set so they work on the file system in my local environment.

**Comment by xiaojoey** [comment]
I updated dependencies and replaced deprecated packages. Reported vulnerabilities should be fixed.

**Comment by samseaver** [comment]
OK, given the number of commits, I'm going to merge with `js_dev` and test locally, if I have any further suggestions, you'll have to open a new PR request from the same branch.

**Pull request merged**
